sonar.projectKey=ESLINT
sonar.projectName=ESLINT
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.eslint.reportPaths=eslint-report.json
